# CI脚本

image: node:12.14.0

cache:
  key: 'node_modules'
  paths:
    - node_modules/

stages:
  - init
  - build

job_init:
  stage: init
  cache:
    key: 'node_modules'
    paths:
      - node_modules/
  script:
    - echo "初始化：安装依赖"
    - npm install --unsafe-perm
  only:
    - test
    - master

job_build:
  stage: build
  script:
    - npm run build:${CI_COMMIT_REF_NAME}
  only:
    - test
    - master
  before_script:
    - echo "Gitlab CI开始运行"
  after_script:
    - echo "CI完成 执行后续动作"
